services:
  nginx-gateway:
    image: "$DOCKER_USERNAME/nginx:$TAG"
    container_name: nginx-gateway
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 8080
    # make sure you have this on your host machine
    volumes:
      - /home/ubuntu/website/logs:/var/log/nginx
      - /home/ubuntu/website/nginx/certificates:/etc/letsencrypt
      - /home/ubuntu/website/nginx/certificates-data:/data/certbot
    networks:
      - webnet
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    # make sure you have this on your host machine
    volumes:
      - /home/ubuntu/website/nginx/certificates:/etc/letsencrypt
      - /home/ubuntu/website/nginx/certificates-data:/data/certbot
    entrypoint: >
      sh -c "
        while :; do
          certbot renew;
          sleep 12h & wait $${!};
        done"
    networks:
      - webnet
    restart: on-failure

networks:
  webnet:


