name: Docker CI/CD monitoring

on:
  push:
    branches: [master]
    paths:
      - '.infrastructure/monitoring/**'

jobs:
  build-monitoring:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.set_output.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set short SHA
        id: set_output
        run: echo "short_sha=${GITHUB_SHA::10}" >> $GITHUB_OUTPUT

      - name: Docker TLS Setup + Build Images
        run: |
          cp -r .infrastructure/* .
        
          chmod +x ./docker-tls-setup.sh
          source docker-tls-setup.sh
          
          cd $GITHUB_WORKSPACE/.infrastructure/monitoring
          docker build -t ${{ secrets.DOCKER_USERNAME }}/prometheus:${{ steps.set_output.outputs.short_sha }} .

        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          CERT_PEM: ${{ secrets.CERT_PEM }}
          KEY_PEM: ${{ secrets.KEY_PEM }}
          CA_PEM: ${{ secrets.CA_PEM }}

  deploy-monitoring:
    runs-on: ubuntu-latest
    needs: build-monitoring
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Docker TLS Setup + Docker Compose
        run: |
          cp -r .infrastructure/.docker/* .
          
          chmod +x ./docker-tls-setup.sh
          source docker-tls-setup.sh
          cd $GITHUB_WORKSPACE/.infrastructure/monitoring
          docker-compose up -d
          docker restart nginx-gateway
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          CERT_PEM: ${{ secrets.CERT_PEM }}
          KEY_PEM: ${{ secrets.KEY_PEM }}
          CA_PEM: ${{ secrets.CA_PEM }}
          TAG: ${{ needs.build-monitoring.outputs.short_sha }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
